[project]
name = "moccasin_project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "eth-abi>=5.2.0",
    "eth-utils>=5.3.0",
    "moccasin>=0.4.2",
]
